/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.app.kafka.warehouse.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderShippedRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5798377085220949392L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderShippedRequestAvroModel\",\"namespace\":\"com.ecommerce.app.kafka.warehouse.avro.model\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"warehouseId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"orderStatus\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"AWAITING_PAYMENT\",\"PENDING\",\"PROCESSED\",\"APPROVED\",\"SHIPPED\",\"CONFIRMED\",\"CANCELLING\",\"CANCELLED\"]}},{\"name\":\"orderItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderItemShipped\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<OrderShippedRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderShippedRequestAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderShippedRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderShippedRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderShippedRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderShippedRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderShippedRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderShippedRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderShippedRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID orderId;
  private java.util.UUID warehouseId;
  private java.time.Instant createdAt;
  private com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus orderStatus;
  private java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> orderItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderShippedRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param warehouseId The new value for warehouseId
   * @param createdAt The new value for createdAt
   * @param orderStatus The new value for orderStatus
   * @param orderItems The new value for orderItems
   */
  public OrderShippedRequestAvroModel(java.util.UUID orderId, java.util.UUID warehouseId, java.time.Instant createdAt, com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus orderStatus, java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> orderItems) {
    this.orderId = orderId;
    this.warehouseId = warehouseId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.orderStatus = orderStatus;
    this.orderItems = orderItems;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return warehouseId;
    case 2: return createdAt;
    case 3: return orderStatus;
    case 4: return orderItems;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.util.UUID)value$; break;
    case 1: warehouseId = (java.util.UUID)value$; break;
    case 2: createdAt = (java.time.Instant)value$; break;
    case 3: orderStatus = (com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus)value$; break;
    case 4: orderItems = (java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.util.UUID getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.util.UUID value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'warehouseId' field.
   * @return The value of the 'warehouseId' field.
   */
  public java.util.UUID getWarehouseId() {
    return warehouseId;
  }


  /**
   * Sets the value of the 'warehouseId' field.
   * @param value the value to set.
   */
  public void setWarehouseId(java.util.UUID value) {
    this.warehouseId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'orderStatus' field.
   * @return The value of the 'orderStatus' field.
   */
  public com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus getOrderStatus() {
    return orderStatus;
  }


  /**
   * Sets the value of the 'orderStatus' field.
   * @param value the value to set.
   */
  public void setOrderStatus(com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus value) {
    this.orderStatus = value;
  }

  /**
   * Gets the value of the 'orderItems' field.
   * @return The value of the 'orderItems' field.
   */
  public java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> getOrderItems() {
    return orderItems;
  }


  /**
   * Sets the value of the 'orderItems' field.
   * @param value the value to set.
   */
  public void setOrderItems(java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> value) {
    this.orderItems = value;
  }

  /**
   * Creates a new OrderShippedRequestAvroModel RecordBuilder.
   * @return A new OrderShippedRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder newBuilder() {
    return new com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder();
  }

  /**
   * Creates a new OrderShippedRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderShippedRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder newBuilder(com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder();
    } else {
      return new com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new OrderShippedRequestAvroModel RecordBuilder by copying an existing OrderShippedRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new OrderShippedRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder newBuilder(com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel other) {
    if (other == null) {
      return new com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder();
    } else {
      return new com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderShippedRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderShippedRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<OrderShippedRequestAvroModel> {

    private java.util.UUID orderId;
    private java.util.UUID warehouseId;
    private java.time.Instant createdAt;
    private com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus orderStatus;
    private java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> orderItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[1].schema(), other.warehouseId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[3].schema(), other.orderStatus);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.orderItems)) {
        this.orderItems = data().deepCopy(fields()[4].schema(), other.orderItems);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderShippedRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[1].schema(), other.warehouseId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[3].schema(), other.orderStatus);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.orderItems)) {
        this.orderItems = data().deepCopy(fields()[4].schema(), other.orderItems);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.util.UUID getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder setOrderId(java.util.UUID value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'warehouseId' field.
      * @return The value.
      */
    public java.util.UUID getWarehouseId() {
      return warehouseId;
    }


    /**
      * Sets the value of the 'warehouseId' field.
      * @param value The value of 'warehouseId'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder setWarehouseId(java.util.UUID value) {
      validate(fields()[1], value);
      this.warehouseId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'warehouseId' field has been set.
      * @return True if the 'warehouseId' field has been set, false otherwise.
      */
    public boolean hasWarehouseId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'warehouseId' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder clearWarehouseId() {
      warehouseId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderStatus' field.
      * @return The value.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus getOrderStatus() {
      return orderStatus;
    }


    /**
      * Sets the value of the 'orderStatus' field.
      * @param value The value of 'orderStatus'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder setOrderStatus(com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus value) {
      validate(fields()[3], value);
      this.orderStatus = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderStatus' field has been set.
      * @return True if the 'orderStatus' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderStatus' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder clearOrderStatus() {
      orderStatus = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderItems' field.
      * @return The value.
      */
    public java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> getOrderItems() {
      return orderItems;
    }


    /**
      * Sets the value of the 'orderItems' field.
      * @param value The value of 'orderItems'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder setOrderItems(java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped> value) {
      validate(fields()[4], value);
      this.orderItems = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'orderItems' field has been set.
      * @return True if the 'orderItems' field has been set, false otherwise.
      */
    public boolean hasOrderItems() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'orderItems' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.OrderShippedRequestAvroModel.Builder clearOrderItems() {
      orderItems = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderShippedRequestAvroModel build() {
      try {
        OrderShippedRequestAvroModel record = new OrderShippedRequestAvroModel();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.util.UUID) defaultValue(fields()[0]);
        record.warehouseId = fieldSetFlags()[1] ? this.warehouseId : (java.util.UUID) defaultValue(fields()[1]);
        record.createdAt = fieldSetFlags()[2] ? this.createdAt : (java.time.Instant) defaultValue(fields()[2]);
        record.orderStatus = fieldSetFlags()[3] ? this.orderStatus : (com.ecommerce.app.kafka.warehouse.avro.model.OrderStatus) defaultValue(fields()[3]);
        record.orderItems = fieldSetFlags()[4] ? this.orderItems : (java.util.List<com.ecommerce.app.kafka.warehouse.avro.model.OrderItemShipped>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderShippedRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderShippedRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderShippedRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<OrderShippedRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










