/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.app.kafka.warehouse.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentProofUploadAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3222255937735713458L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentProofUploadAvroModel\",\"namespace\":\"com.ecommerce.app.kafka.warehouse.avro.model\",\"fields\":[{\"name\":\"paymentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"paymentOrderStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentOrderStatus\",\"symbols\":[\"PENDING\",\"CANCELLED\",\"PAID\",\"FAILED\",\"AWAITING_PAYMENT\",\"UNDER_REVIEW\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PaymentProofUploadAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentProofUploadAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentProofUploadAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentProofUploadAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentProofUploadAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentProofUploadAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentProofUploadAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentProofUploadAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentProofUploadAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID paymentId;
  private java.util.UUID orderId;
  private java.time.Instant createdAt;
  private com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus paymentOrderStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentProofUploadAvroModel() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param orderId The new value for orderId
   * @param createdAt The new value for createdAt
   * @param paymentOrderStatus The new value for paymentOrderStatus
   */
  public PaymentProofUploadAvroModel(java.util.UUID paymentId, java.util.UUID orderId, java.time.Instant createdAt, com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus paymentOrderStatus) {
    this.paymentId = paymentId;
    this.orderId = orderId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.paymentOrderStatus = paymentOrderStatus;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return orderId;
    case 2: return createdAt;
    case 3: return paymentOrderStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.util.UUID)value$; break;
    case 1: orderId = (java.util.UUID)value$; break;
    case 2: createdAt = (java.time.Instant)value$; break;
    case 3: paymentOrderStatus = (com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.util.UUID getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.util.UUID value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.util.UUID getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.util.UUID value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'paymentOrderStatus' field.
   * @return The value of the 'paymentOrderStatus' field.
   */
  public com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus getPaymentOrderStatus() {
    return paymentOrderStatus;
  }


  /**
   * Sets the value of the 'paymentOrderStatus' field.
   * @param value the value to set.
   */
  public void setPaymentOrderStatus(com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus value) {
    this.paymentOrderStatus = value;
  }

  /**
   * Creates a new PaymentProofUploadAvroModel RecordBuilder.
   * @return A new PaymentProofUploadAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder newBuilder() {
    return new com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder();
  }

  /**
   * Creates a new PaymentProofUploadAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentProofUploadAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder newBuilder(com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder other) {
    if (other == null) {
      return new com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder();
    } else {
      return new com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new PaymentProofUploadAvroModel RecordBuilder by copying an existing PaymentProofUploadAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new PaymentProofUploadAvroModel RecordBuilder
   */
  public static com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder newBuilder(com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel other) {
    if (other == null) {
      return new com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder();
    } else {
      return new com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentProofUploadAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentProofUploadAvroModel>
    implements org.apache.avro.data.RecordBuilder<PaymentProofUploadAvroModel> {

    private java.util.UUID paymentId;
    private java.util.UUID orderId;
    private java.time.Instant createdAt;
    private com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus paymentOrderStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.paymentOrderStatus)) {
        this.paymentOrderStatus = data().deepCopy(fields()[3].schema(), other.paymentOrderStatus);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentProofUploadAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentOrderStatus)) {
        this.paymentOrderStatus = data().deepCopy(fields()[3].schema(), other.paymentOrderStatus);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.util.UUID getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder setPaymentId(java.util.UUID value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.util.UUID getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder setOrderId(java.util.UUID value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentOrderStatus' field.
      * @return The value.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus getPaymentOrderStatus() {
      return paymentOrderStatus;
    }


    /**
      * Sets the value of the 'paymentOrderStatus' field.
      * @param value The value of 'paymentOrderStatus'.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder setPaymentOrderStatus(com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus value) {
      validate(fields()[3], value);
      this.paymentOrderStatus = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentOrderStatus' field has been set.
      * @return True if the 'paymentOrderStatus' field has been set, false otherwise.
      */
    public boolean hasPaymentOrderStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paymentOrderStatus' field.
      * @return This builder.
      */
    public com.ecommerce.app.kafka.warehouse.avro.model.PaymentProofUploadAvroModel.Builder clearPaymentOrderStatus() {
      paymentOrderStatus = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentProofUploadAvroModel build() {
      try {
        PaymentProofUploadAvroModel record = new PaymentProofUploadAvroModel();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.util.UUID) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.util.UUID) defaultValue(fields()[1]);
        record.createdAt = fieldSetFlags()[2] ? this.createdAt : (java.time.Instant) defaultValue(fields()[2]);
        record.paymentOrderStatus = fieldSetFlags()[3] ? this.paymentOrderStatus : (com.ecommerce.app.kafka.warehouse.avro.model.PaymentOrderStatus) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentProofUploadAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentProofUploadAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentProofUploadAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<PaymentProofUploadAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










