DROP SCHEMA IF EXISTS "order" CASCADE;

DROP SCHEMA IF EXISTS "user" CASCADE;
CREATE SCHEMA "user";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS "user".warehouses CASCADE;

CREATE TABLE warehouses (
    id UUID PRIMARY KEY
);
