apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "kong-database"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "kong"
            - name: KONG_PG_DATABASE
              value: "kong"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
            - name: KONG_PROXY_LISTEN_SSL
              value: "0.0.0.0:8443"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_ADMIN_GUI_URL
              value: "http://0.0.0.0:8002"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong
      volumes:
        - name: kong-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: default
  labels:
    app: kong
spec:
  type: LoadBalancer
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-ssl
      port: 8444
      targetPort: 8444
